FRONTENDBOOTCAMP-13th/EagleSauce

.gitignore
src/style.css

💄style : style.css/root설정

---

index.html
src/components/main-banner.html
src/components/main-bottle.html
src/components/main-footer.html
src/components/main-header.html
vite.config.js

- 메인페이지 작업을 위한 component파일 구분
- 
resolves #

💄style : componen-build

---

src/components/main-banner.html

💄style: 1차 main-banner.html

---

src/components/main-footer.html

- 저녁 커밋 (미완성)
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #

🎨 feat: footer 작업

---

src/components/main-banner.html

💄style: main-banner components 완성

---

src/components/main-bottle.html
src/style.css

-style.css 변수 추가
-main-bottle.html 배너영역 수정
resolves #10

:lipstick:style: 메인페이지 배너영역 수정

---

src/components/main-footer.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #

💄style : 메인페이지 푸터

---

README.md

📝 docs: README에 내용 추가

---

index.html
src/components/main-footer.html
src/main.js
src/style.css

- 이어 붙이는 뼈대 작업만 해놓았습니다
- z-index 등 수정이 필요한 곳이 보여서 이어서 수정 작업 진행하려고합니다
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #

💄style : main layout

---

index.html
src/pages/search.html

💄style: 서치페이지 중간커밋

---

index.html

:lipstick:style: add index.html file

---

src/pages/community-event.html
src/style.css

- style.css 오타 수정
- 커뮤니티/이벤트 페이지 스타일 추가
resolves #39

:lipstick:style Add Community event page

---

index.html
src/pages/cart.html
src/style.css

-index.html에 cart.html 링크 연결
-style.css 변수 추가 (컬러, 애니메이션)
-cart.html css 등 사용자 디자인 변경
resolves #46

:lipstick:style: 카트 페이지 제작

---

src/components/shop-section12.html
src/components/shop-section13.html

-shop-section13 타이틀 수정
-shop-section12 중간 작업과정 커밋
resolves #69

:lipstick:style shop-section12 중간 커밋

---

index.html
src/components/shop-section03.html

💄style: shop-pyogoruffle 03-section 완성

---

src/components/shop-section11.html

-shop-section11 제작
resolves #68

:lipstick:style: shop section-11 제작

---

src/components/shop-section02.html

💄style: shop-pyogoruffle-02section-pjh

---

index.html
src/components/shop-section03.html
src/pages/shop-hotnkit.html
src/pages/shop-parmesan.html
src/pages/shop-pyogo.html
src/pages/shop-shrimp.html
src/style.css

- index.html연결
- shop-항목연결
- style.css bg추가
resolves #89

💄style : pyogo기본페이지세팅

---

src/pages/shop-pyogo.html

-shop-pyogoruffle rolling text 추가
resolves #94

:lipstick:style: shop-pyogoruffle 움직이는 텍스트 추가페이지세팅

---

src/components/shop-section07.html

💄style: shop-pyogoruffle-07section 완성(애니메이션 추가 필요)

---

src/pages/shop-pyogo.html

💄style : shop/pyogoruffle완성

---

package.json

- package.json 추가설정
resolves #1

🛠️ build : package.json 추가설정

---

src/pages/shop-pyogo.html

-flex order를 통한 제품 이미지 컨테이너 컴포넌트화
-xl, 2xl과 같은 변수를 px로 변환
- x[] CSS 등 사용자 UI 디자인 변경
resolves #102

:recycle:refactor: refactoring shop-section-10~11

---

src/components/shop-section02.html

♻️refactor : section2-코드리팩토링

---

src/components/shop-section01.html

♻️refactor: shop-section01 코드 리팩토링

---

src/components/shop-section13.html

- 문법 및 구조 개선
- 접근성 개선
- 중복 코드 제거거
resolves #110

110 shop productsection 13 refactor 코드수정 코드리팩토링

---

src/components/shop-section02.html

- section 내 aria-labelledby추가
resolves #111

♻️refactor: shop-section02 코드 리팩토링

---

src/components/shop-section05.html

♻️refactor: shop-section05 코드 리팩토링

---

src/components/shop-section12.html
src/components/shop-section13.html

-클래스 구조화
-접근성 개선
-shop-productsection-13 <h2>텍스트 수정정
resolves #114

:recycle:refactor: shop-productsection-12  코드 리펙토링

---

src/components/shop-section06.html

♻️refactor: shop-section06 코드 리팩토링

---

src/components/shop-section03.html

♻️refactor: shop-section03 코드 리팩토링

---

src/components/shop-section09.html

♻️refactor: shop-section09 코드 리팩토링

---

src/components/shop-section08.html

♻️refactor: shop-section08 코드 리팩토링

---

src/pages/community-napolimatfia.html
src/pages/shop-all_products.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #

♻️refactor: shop-all products 코드 리팩토링

---

src/components/shop-section12.html

- 반응형 텍스트 높이 조정
- sr-only추가
- 버튼링크연결 수정
resolves #132

♻️refactor: shop-section12

---

src/components/shop-section11.html

-alt, aria-label 피드백 반영영
resolves #139

:recycle:refactor: shop-section11 코드 리펙토링

---

src/pages/community-napolimatfia.html
src/pages/shop-all_products.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #137

♻️refactor: [COMMUNITY] napolimatfia/refactor

---

src/pages/community-napolimatfia.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #

:recycle: refactor: [COMMUMITY] napolimatfia/refactor 링크연결

---

src/pages/about-ourbrand.html

- title
- arialabelledby
- alt
- loading:lazy
- 텍스트크기조정
resolves #151

♻️refactor : our-brand

---

src/pages/about-inquiry.html
src/pages/community-faq.html

-주석 추가
-사용되지 않는 class 삭제
-about-inquiry.html body에 부여되어있던 overflow-hidden 속성 삭제제
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #160

:recycle:refactor community-faq 코드 리펙토링

---

src/pages/community-event.html
src/pages/community-eventboard.html
src/pages/community-napolimatfia.html

- title추가설정
- img-lazyload
resolves #167

♻️refactor : event2

---

src/components/main-header.html
src/js/header.js

♻️refactor : Header/refactor psy

---

src/pages/community-faq.html
src/pages/search.html
src/style.css

-타이틀 수정
-접근성 개선
-백그라운드 이미지 변수화
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #164

:recycle:refacotr: extra-search 코드 리펙토링

---

src/pages/cart.html

-링크 연결
-접근성 개선 (aria-labeledby)추가
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #174

:recycle:refactor: extra-cart 코드 리펙토링

---

src/pages/search.html

♻️refactor : search refactor

---

src/pages/about-inquiry.html
src/pages/cart.html
src/pages/community-napolimatfia.html
src/pages/home.html

-접근성 향상 측면에서 (aria-label) 추가
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #177

:recycle:refactor community-napolimatfia 코드 리펙토링

---

src/pages/community-review.html

♻️refactor: community-review-refactor

---

src/main.js
src/pages/about-inquiry.html
src/pages/about-ourbrand.html
src/pages/cart.html
src/pages/community-event.html
src/pages/community-eventboard.html
src/pages/community-faq.html
src/pages/community-napolimatfia.html
src/pages/community-qna.html
src/pages/community-recipes_and_paring.html
src/pages/community-review.html
src/pages/home.html
src/pages/join-login.html
src/pages/search.html
src/pages/shop-all_products.html
src/pages/shop-giftbag.html
src/pages/shop-hotnkit.html
src/pages/shop-parmesan.html
src/pages/shop-pyogo.html
src/pages/shop-shrimp.html
src/style.css

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #187

♻️refactor: all page head

---

src/components/community-reviewtext.html
src/pages/index_2.html

💄style : index2-component페이지관련

---

src/pages/shop-giftbag.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #194

♻️refactor : refactor-bag

---

index.html
src/style.css

💄style : stylecss추가

---

src/components/pages-tag.html
src/js/footer.js
src/style.css

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #

♻️refactor: footer 이미지 수정

---

src/components/main-header.html
src/js/main-header.js
src/js/sub-header.js

- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #207

🐛 bug : 배포 시 이미지 경로 문제 재설정

---

src/components/main-header.html
src/js/main-header.js
src/js/sub-header.js

- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #

🐛 bug : 메뉴 닫힘현상 설정

---

src/components/main-header.html
src/js/main-header.js
src/js/sub-header.js
src/pages/shop-hotnkit.html
src/pages/shop-shrimp.html

Shop menu psy

---

src/pages/shop-parmesan.html
src/pages/shop-pyogo.html
src/pages/shop-shrimp.html
src/style.css

🐛 bug : animation끊김현상조정

---

src/pages/home.html

-팝업 링크 연결
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #222

:lipstick:style: 메인 페이지 컴포넌트 팝업 링크 연결

---

src/components/showcase-parmesan-popup.html
src/components/showcase-pyogo-popup.html
src/components/showcase-shrimp-popup.html

♻️ refactor : 코드추가수정

---

index.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #232

:recycle:refactor: 인덱스 페이지 멤버소개 깃헙 링크 수정

---

src/pages/about-inquiry.html

-<a>안에 <button>을 사용한점 수정
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #234

:recycle:refactor: 인덱스 코드 리펙토링

---

index.html
src/components/modal.html
src/components/showcase-parmesan-popup.html
src/components/showcase-pyogo-popup.html
src/components/showcase-shrimp-popup.html
src/pages/home.html

- [] 새로운 기능 추가
- [] 문서 수정
resolves #

:recycle: refactor: page repactor

---

index.html
src/js/index.js
src/style.css

- index.html
1. img : aria-hidden add (alt="" edit)
2. button : aria-pressed add
3. modal : lines move
- index.js : js edit
- styls.css : hot-brand-color edit
1. 이미지  
- 이미지 대체텍스트 일부 수정 
- 장식 이미지의 경우 aria-hidden: true -> 이 경우 대체텍스트 공란 처리(alt="")
2. 모바일 및 PC화면
- 모바일 span처리되어 있던 tag -> button으로 변경
- 모바일 및 PC : 버튼 상호작용에 따른 화면 변경으로 aria-label 기능적인 부분 구체화
- 웹접근성 개선을 위한 aria-pressed 속성 추가로 현재 선택되어 있는 값이 무엇인지 알게함 
3. Style.css 
- hot-brand-color 의 변경 : 메인 색상을 좀 더 어둡게 변경함 ->  텍스트와 배경색 사이의 대비(Contrast) 개선
resolves #270

🖥️ accessibility: index.html edit

---

index.html
src/components/main-showcase.html
src/components/pages-rollingtext.html
src/components/shop-section04.html
src/components/shop-section06.html
src/components/showcase-parmesan-popup.html
src/components/showcase-pyogo-popup.html
src/components/showcase-shrimp-popup.html
src/pages/cart.html
src/pages/community-event.html
src/pages/community-napolimatfia.html
src/pages/home.html
src/pages/shop-giftbag.html
src/pages/shop-hotnkit.html
src/pages/shop-parmesan.html
src/pages/shop-pyogo.html
src/pages/shop-shrimp.html

- 웹접근성 개선 animation 
- index.html 문구추가
resolves #

✨ feat : Animate reduce/psy

---

index.html
src/components/community-napolimatfia-hashtag.html
src/components/main-showcase.html
src/components/pages-rollingtext.html
src/components/shop-section04.html
src/components/shop-section06.html
src/components/showcase-parmesan-popup.html
src/components/showcase-pyogo-popup.html
src/components/showcase-shrimp-popup.html
src/pages/cart.html
src/pages/community-event.html
src/pages/community-napolimatfia.html
src/pages/home.html
src/pages/shop-giftbag.html
src/pages/shop-hotnkit.html
src/pages/shop-parmesan.html
src/pages/shop-pyogo.html
src/pages/shop-shrimp.html

🐛 bug : motion-reduce edit

---

index.html
src/components/community-napolimatfia-hashtag.html
src/components/main-showcase.html
src/components/pages-rollingtext.html
src/components/shop-section04.html
src/components/shop-section06.html
src/components/showcase-parmesan-popup.html
src/components/showcase-pyogo-popup.html
src/components/showcase-shrimp-popup.html
src/pages/cart.html
src/pages/community-event.html
src/pages/community-napolimatfia.html
src/pages/home.html
src/pages/shop-giftbag.html
src/pages/shop-hotnkit.html
src/pages/shop-parmesan.html
src/pages/shop-pyogo.html
src/pages/shop-shrimp.html

🚀 depoly : main update
